<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Base64Tool</AssemblyName>
    <RootNamespace>Base64Tool</RootNamespace>
    <RestoreSources>../nupkgs</RestoreSources>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DITT.SDK" Version="1.0.0" />
  </ItemGroup>
</Project>
